#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"ClusterClass"})
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
spec:
  #@overlay/match missing_ok=True
  variables:
  #@overlay/remove
  #@overlay/match by=overlay.map_key("name"),missing_ok=True
  - name: podSecurityStandard
  #@overlay/append
  - name: podSecurityStandard
    required: false
    schema:
      openAPIV3Schema:
        type: object
        default: {}
        properties:
          deactivated:
            type: boolean
            description: "deactivated disables the patches for Pod Security Standard via AdmissionConfiguration."
          enforce:
            type: string
            enum: ["", "privileged", "baseline", "restricted"]
            description: "enforce sets the level for the enforce PodSecurityConfiguration mode. One of \"\", privileged, baseline, restricted."
            nullable: true
          enforceVersion:
            type: string
            #! Version defaults to v1.24 for now. When v1.25 is part of tanzu-framework, the defaulting should be done
            #! by a defaulting webhook instead for extended logic.
            default: "v1.24"
            description: "enforceVersion sets the version for the enforce PodSecurityConfiguration mode."
          audit:
            type: string
            enum: ["", "privileged", "baseline", "restricted"]
            description: "audit sets the level for the audit PodSecurityConfiguration mode. One of \"\", privileged, baseline, restricted."
            nullable: true
          auditVersion:
            type: string
            #! Version defaults to v1.24 for now. When v1.25 is part of tanzu-framework, the defaulting should be done
            #! by a defaulting webhook instead for extended logic.
            default: "v1.24"
            description: "auditVersion sets the version for the audit PodSecurityConfiguration mode."
          warn:
            type: string
            enum: ["", "privileged", "baseline", "restricted"]
            description: "warn sets the level for the warn PodSecurityConfiguration mode. One of \"\", privileged, baseline, restricted."
            nullable: true
          warnVersion:
            type: string
            #! Version defaults to v1.24 for now. When v1.25 is part of tanzu-framework, the defaulting should be done
            #! by a defaulting webhook instead for extended logic.
            default: "v1.24"
            description: "warnVersion sets the version for the warn PodSecurityConfiguration mode."
          exemptions:
            type: object
            description: "exemption configuration for the PodSecurityConfiguration."
            properties:
              namespaces:
                type: array
                items:
                  type: string
                description: "namespaces excluded to apply PodSecurityConfiguration Admission."
  #@overlay/remove
  #@overlay/match by=overlay.map_key("name"),missing_ok=True
  - name: eventRateLimitConf
  #@overlay/append
  - name: eventRateLimitConf
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: ""
  #@overlay/match missing_ok=True
  patches:
  #@overlay/remove
  #@overlay/match by=overlay.map_key("name"),missing_ok=True
  - name: admissionConfiguration
  #@overlay/append
  - name: admissionConfiguration
    description: "Adds an admission configuration for kube-apiserver."
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/extraArgs/admission-control-config-file"
        value: "/etc/kubernetes/admission-control-config.yaml"
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/extraVolumes/-"
        valueFrom:
          template: |
            - name: admin-control-conf
              hostPath: /etc/kubernetes/admission-control-config.yaml
              mountPath: /etc/kubernetes/admission-control-config.yaml
              readOnly: true
              pathType: "File"
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/files/-"
        valueFrom:
          template: |-
            path: /etc/kubernetes/admission-control-config.yaml
            content: |-
              {{ $namespace_exemptions := printf "%q, %q" "kube-system" "tkg-system" -}}
              {{ $defaultWarnAudit := "baseline" }}
              {{- if .podSecurityStandard.exemptions.namespaces -}}
                {{ range $namespace := .podSecurityStandard.exemptions.namespaces -}}
                  {{ $namespace_exemptions = printf "%s, %q" $namespace_exemptions $namespace -}}
                {{- end -}}
              {{- end -}}
              apiVersion: apiserver.config.k8s.io/v1
              kind: AdmissionConfiguration
              plugins:
              {{ if and (not .podSecurityStandard.deactivated) (semverCompare ">= v1.24" .builtin.controlPlane.version) }}
              - name: PodSecurity
                configuration:
                  apiVersion: pod-security.admission.config.k8s.io/v1beta1
                  kind: PodSecurityConfiguration
                  defaults:
                    enforce: "{{ if .podSecurityStandard.enforce -}}
                        {{ .podSecurityStandard.enforce }}
                      {{- end }}"
                    enforce-version: "{{ .podSecurityStandard.enforceVersion -}}"
                    audit: "{{ if .podSecurityStandard.audit -}}
                        {{ .podSecurityStandard.audit }}
                      {{- else -}}
                        {{ $defaultWarnAudit }}
                      {{- end }}"
                    audit-version: "{{ .podSecurityStandard.auditVersion -}}"
                    warn: "{{ if .podSecurityStandard.warn -}}
                        {{ .podSecurityStandard.warn }}
                      {{- else -}}
                        {{ $defaultWarnAudit }}
                      {{- end }}"
                    warn-version: "{{ .podSecurityStandard.warnVersion -}}"
                  exemptions:
                    usernames: []
                    runtimeClasses: []
                    namespaces: [{{ $namespace_exemptions }}]
              {{- end }}
              {{ if .eventRateLimitConf }}
              - name: EventRateLimit
                path: eventConfig.yaml
              {{- end }}
    enabledIf: '{{ or (and (not .podSecurityStandard.deactivated) (semverCompare ">= v1.24" .builtin.controlPlane.version)) (.eventRateLimitConf) }}'
  #@overlay/remove
  #@overlay/match by=overlay.map_key("name"),missing_ok=True
  - name: eventRateLimitConf
  #@overlay/append
  - name: eventRateLimitConf
    description: "Adds an admission configuration for EventRateLimit."
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/extraArgs/-"
        valueFrom:
          template: |
            {{ $enableAdmissionPlugin := false }}
            {{- range $key, $val := .apiServerExtraArgs }}
            {{- if eq $key "enable-admission-plugin" }}
            {{- $enableAdmissionPlugin = true }}
            {{- end }}
            {{- end }}
            {{- if not $enableAdmissionPlugin }}
            enable-admission-plugins: "NodeRestriction,EventRateLimit"
            {{- end }}
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/extraVolumes/-"
        valueFrom:
          template: |
            - name: event-conf
              hostPath: /etc/kubernetes/eventConfig.yaml
              mountPath: /etc/kubernetes/eventConfig.yaml
      - op: add
        path: "/spec/template/spec/kubeadmConfigSpec/files/-"
        valueFrom:
          template: |-
            path: /etc/kubernetes/eventConfig.yaml
            encoding: base64
            content: "{{ .eventRateLimitConf}}"
    enabledIf: '{{ .eventRateLimitConf }}'
